function [normalizationFactorOfProjectionSubset] = calculateNormalizationImageOfProjectionSubset(thetaOfProjectionSubset, ...
   boolColGeoMode, cenOfRotToFrontOfColOfProjSubset, lenOfColHole ,backOfColToProjPlane, radiusOfColHole, ...
   boolAttMode, attMap, detectFWHM, ...
   xImageDimen, yImageDimen, zImageDimen, xProjDimen, zProjDimen, ...
   xImageWidth, yImageWidth, zImageWidth, xProjWidth, zProjWidth)

% 针对一个投影子集进行反投影的归一化因子图像的计算，对应OSEM迭代；若不分子集则为全部投影，对应MLEM迭代
% 输入参数：
% @投影子集对应的角度数组，thetaOfProjectionSubset
% @反投影函数需要的输入参数（不包括角度 theta，因为已经放在 thetaOfProjectionSubset 数组中；也不包括投影比值 projectionRatio，因为在函数内部会定义一个新的子集对应的投影比值）
  % backwardProjection (projectionRatio, theta, ...
  % boolColGeoMode, cenOfRotToFrontOfCol, lenOfColHole ,backOfColToProjPlane, radiusOfColHole, ...
  % boolAttMode, attMap, detectFWHM, ...
  % xImageDimen, yImageDimen, zImageDimen, xProjDimen, zProjDimen, ...
  % xImageWidth, yImageWidth, zImageWidth, xProjWidth, zProjWidth)

% 输出参数：
% @特定的投影子集对应的归一化因子图像，normalizationFactorOfProjectionSubset


    %每个子集中有多少个投影，对应多少个特定的投影角度，投影帧数（一个探头在一个角度采集一段时间得到的投影图像称为一帧）
    numOfFrameInOneSubset = numel(thetaOfProjectionSubset);

    %对整个子集对应的投影比值初始化，全为1
    projectionRatioSubset = ones(xProjDimen,zProjDimen,numOfFrameInOneSubset);

    normalizationFactorOfProjectionSubset = zeros(xImageDimen,yImageDimen,zImageDimen);

    parfor n=1:numOfFrameInOneSubset
        normalizationFactorOfProjectionSubset = normalizationFactorOfProjectionSubset + backwardProjection (squeeze( projectionRatioSubset(:,:,n) ), thetaOfProjectionSubset(n), ...
           boolColGeoMode, cenOfRotToFrontOfColOfProjSubset(n), lenOfColHole ,backOfColToProjPlane, radiusOfColHole, ...
           boolAttMode, attMap, detectFWHM, ...
           xImageDimen, yImageDimen, zImageDimen, xProjDimen, zProjDimen, ...
           xImageWidth, yImageWidth, zImageWidth, xProjWidth, zProjWidth);
    end

end

