function [reconParameterStruct] = defineReconParameterStruct()

%手动输入重建参数，一部分重建参数从投影DICOM文件的头信息中读取出来，一部分重建参数自己手动定义即可

    field_projectionFileName = 'projectionFileName';          value_projectionFileName = 'TomoSPECTrawdata';
    field_xProjectionDimension = 'xProjectionDimension';      value_xProjectionDimension = 128;
    field_zProjectionDimension = 'zProjectionDimension';      value_zProjectionDimension = value_xProjectionDimension;
    field_xProjectionWidth = 'xProjectionWidth';              value_xProjectionWidth = 4.418; %单位：毫米,mm
    field_zProjectionWidth = 'zProjectionWidth';              value_zProjectionWidth = value_xProjectionWidth;
    field_numberOfProjectionView = 'numberOfProjectionView';  value_numberOfProjectionView = 60;
    field_rotationAngleRange = 'rotationAngleRange';          value_rotationAngleRange = 360;
    field_rotationStartAngle = 'rotationStartAngle';          value_rotationStartAngle = 0.81; %单位：度
    
    field_centerOfRotationToFrontOfCollimator = 'centerOfRotationToFrontOfCollimator';  value_centerOfRotationToFrontOfCollimator = 303; %单位：毫米,mm
    
    %复杂轨道模式开关，若为true，则需要在 value_complexOrbitParameter 中填写一个二维数组，第一列代表投影角度，第二列代表旋转中心到准直器前表面的距离
    field_boolComplexOrbitMode = 'boolComplexOrbitMode';      value_boolComplexOrbitMode = false;
    field_complexOrbitParameter = 'complexOrbitParameter';    value_complexOrbitParameter = [225,307;...
                                                                                             228,307];
                                                                                       
    field_outputReconImageFileName = 'outputReconImageFileName';                    value_outputReconImageFileName = 'reconImage.img';
    field_initializationReconImageFileName = 'initializationReconImageFileName';    value_initializationReconImageFileName = 'reconImage.img.iter2000.subset10.scat1.fwd4.bwd4';
    
    field_xImageDimension = 'xImageDimension';                value_xImageDimension = value_xProjectionDimension;
    field_yImageDimension = 'yImageDimension';                value_yImageDimension = value_xImageDimension;
    field_zImageDimension = 'zImageDimension';                value_zImageDimension = value_xImageDimension;
    field_xImageWidth = 'xImageWidth';                        value_xImageWidth = value_xProjectionWidth ;
    field_yImageWidth = 'yImageWidth';                        value_yImageWidth = value_xImageWidth;
    field_zImageWidth = 'zImageWidth';                        value_zImageWidth = value_xImageWidth;
    
    field_iterationTimes = 'iterationTimes';                  value_iterationTimes = 2;
    field_numberOfSubsets = 'numberOfSubsets';                value_numberOfSubsets = 10;
    
    field_numberOfIterationIntervalToSave = 'numberOfIterationIntervalToSave';  value_numberOfIterationIntervalToSave = 2;  %迭代n次存储重建图像，n是 numberOfIterationIntervalToSave 值的整数倍
    
    %散射校正在投影域进行，前投影反投影均有效
    field_scatterCorrectionMode = 'scatterCorrectionMode';                     value_scatterCorrectionMode = false;     
    field_scatterEnergyWindowLowLimit = 'scatterEnergyWindowLowLimit';          value_scatterEnergyWindowLowLimit = 114;
    field_scatterEnergyWindowHighLimit = 'scatterEnergyWindowHighLimit';        value_scatterEnergyWindowHighLimit = 126;
    field_mainEnergyWindowLowLimit = 'mainEnergyWindowLowLimit';                value_mainEnergyWindowLowLimit = 126.45;
    field_mainEnergyWindowHighLimit ='mainEnergyWindoHighLimit';                value_mainEnergyWindowHighLimit = 154.55;
    
    % 前投影建模考虑的物理效应： 1.探测器分辨率校正 2.衰减校正 + 探测器分辨率校正 3.准直器校正 + 探测器分辨率校正 4.衰减校正 + 准直器校正 + 探测器分辨率校正
    field_forwardProjectionPhysicsMode = 'forwardProjectionPhysicsMode';        value_forwardProjectionPhysicsMode = 4;
    
    % 反投影建模考虑的物理效应： 1.探测器分辨率校正 2.衰减校正 + 探测器分辨率校正 3.准直器校正 + 探测器分辨率校正 4.衰减校正 + 准直器校正 + 探测器分辨率校正
    field_backwardProjectionPhysicsMode = 'backwardProjectionPhysicsMode';      value_backwardProjectionPhysicsMode = 4;

    
    field_attenuationMapFileName = 'attenuationMapFileName';                                    value_attenuationMapFileName = 'attenuationMapRegistered.dat';
    
    
    field_distanceCollimatorBackToProjectionPlane = 'distanceCollimatorBackToProjectionPlane';  value_distanceCollimatorBackToProjectionPlane = 10; %单位：毫米
    
    field_collimatorHoleLength = 'collimatorHoleLength';                  value_collimatorHoleLength = 35;         %单位：毫米
    field_collimatorHoleDiameter = 'collimatorHoleDiameter';              value_collimatorHoleDiameter = 1.5;      %单位：毫米
    field_detectorIntrinsicResolution = 'detectorIntrinsicResolution';    value_detectorIntrinsicResolution = 4; %单位：毫米
    

    
    reconParameterStruct = struct(field_projectionFileName,     value_projectionFileName, ...
                                  field_xProjectionDimension,   value_xProjectionDimension, ...
                                  field_zProjectionDimension,   value_zProjectionDimension, ...
                                  field_xProjectionWidth,       value_xProjectionWidth, ...
                                  field_zProjectionWidth,       value_zProjectionWidth, ...
                                  field_numberOfProjectionView, value_numberOfProjectionView, ...
                                  field_rotationAngleRange,     value_rotationAngleRange, ...
                                  field_rotationStartAngle,     value_rotationStartAngle, ...
                                  field_centerOfRotationToFrontOfCollimator, value_centerOfRotationToFrontOfCollimator, ...
                                  field_boolComplexOrbitMode,   value_boolComplexOrbitMode, ...
                                  field_complexOrbitParameter,  value_complexOrbitParameter, ...
                                  field_outputReconImageFileName,         value_outputReconImageFileName, ...
                                  field_initializationReconImageFileName, value_initializationReconImageFileName, ...
                                  field_xImageDimension,        value_xImageDimension, ...
                                  field_yImageDimension,        value_yImageDimension, ...
                                  field_zImageDimension,        value_zImageDimension, ...
                                  field_xImageWidth,            value_xImageWidth, ...
                                  field_yImageWidth,            value_yImageWidth, ...
                                  field_zImageWidth,            value_zImageWidth, ...
                                  field_iterationTimes,         value_iterationTimes, ...
                                  field_numberOfSubsets,        value_numberOfSubsets, ...
                                  field_numberOfIterationIntervalToSave, value_numberOfIterationIntervalToSave, ...
                                  field_scatterCorrectionMode,  value_scatterCorrectionMode, ...
                                  field_scatterEnergyWindowLowLimit,   value_scatterEnergyWindowLowLimit, ...
                                  field_scatterEnergyWindowHighLimit,  value_scatterEnergyWindowHighLimit, ...
                                  field_mainEnergyWindowLowLimit,      value_mainEnergyWindowLowLimit, ...
                                  field_mainEnergyWindowHighLimit,      value_mainEnergyWindowHighLimit, ...
                                  field_forwardProjectionPhysicsMode,  value_forwardProjectionPhysicsMode, ...
                                  field_backwardProjectionPhysicsMode, value_backwardProjectionPhysicsMode, ...
                                  field_attenuationMapFileName, value_attenuationMapFileName, ...
                                  field_distanceCollimatorBackToProjectionPlane, value_distanceCollimatorBackToProjectionPlane, ...
                                  field_collimatorHoleLength,   value_collimatorHoleLength, ...
                                  field_collimatorHoleDiameter, value_collimatorHoleDiameter, ...
                                  field_detectorIntrinsicResolution, value_detectorIntrinsicResolution);
                               


end

